version: '3.8'

services:
  git-backup:
    image: ${REGISTRY:-ghcr.io}/${GITHUB_REPOSITORY:-your-username/git-backup}:${TAG:-latest}
    container_name: git-backup
    restart: unless-stopped
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - ./backups:/app/backups
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
      - ${SSH_KEY_PATH:-~/.ssh}:/root/.ssh:ro
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-secret-key}
      - HOST=0.0.0.0
      - PORT=5000
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GIT_PYTHON_TRACE=${GIT_PYTHON_TRACE:-full}
      - TZ=${TZ:-Asia/Shanghai}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"